#!/bin/bash

source git-commond

# Blatantly copying from https://github.com/yaccz/git-branch-backup/blob/master/bin/git-branch-backup

function main {
    local branch id
    branch=$(git rev-parse --abbrev-ref HEAD) || return

    if [[ "${branch}" == "HEAD" ]] ; then
        echo "There is no branch on HEAD" >&2
        return 1
    fi

    if [[ ${branch} =~ ^.*\.backup[0-9]{1,}$ ]]; then
        echo "HEAD is already a backup" >&2
        return 1
    fi

    id=$(new_backup_id "${branch}") || return

    local backup="${branch}.backup${id}"
    git branch "${backup}" || return
    echo "Created backup branch '${backup}'"
}

main
