#!/bin/bash

function highest_backup_id {
    local branch="${1}"
    [[ "${branch}" == "" ]] && return 1

    local prefix="${branch}.backup"
    git branch --list --color=never "${prefix}*" \
        | sed "s/^..${prefix}//" \
        | sort -nr \
        | head -n1
}

function new_backup_id {
    local branch="${1}"
    local highest=$(highest_backup_id "${branch}") || return
    echo $(( $highest + 1 ))
}

